import { Button, StyleSheet } from 'react-native';

import EditScreenInfo from '../components/EditScreenInfo';
import { Text, View } from '../components/Themed';
import { RootTabScreenProps } from '../types';

import { Notifications, Notification } from 'react-native-notifications';


export default function TabOneScreen({ navigation }: RootTabScreenProps<'TabOne'>) {
  const onPressHandler = () => {
    // let n = new Notification({
    //   title: "Local notification",
    //   body: "This notification was generated by the app!",
    //   extra: "data"
    // });
    //Notifications.registerRemoteNotifications()
    //Notifications.postLocalNotification(n)
    
  }
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Tab One</Text>
      <Button title='Press me!' onPress={onPressHandler}></Button>
      <View style={styles.separator} lightColor="#eee" darkColor="rgba(255,255,255,0.1)" />
      <EditScreenInfo path="/screens/TabOneScreen.tsx" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  separator: {
    marginVertical: 30,
    height: 1,
    width: '80%',
  },
});
